### ISSUE TITLE
Array(some_decorator_object) -> undefined method `to_ary' for ....

### ISSUE THREAD

**Issue by zdenal** [drapergem/draper#115]
Hi Casimir,

when I update gem from 0.9.5 to 0.10.0 then I got this error in places where I use something like: Array(some_decorator_object) or [some_decorator_objects].flatten

Thank you for sharing draper with me.

Sincerely,
Zdenal
